export const GET_PROFILE = "GET_PROFILE";
export const GET_CONNECTED_USER = "GET_CONNECTED_USER";
export const GET_CHAT_ROOM = "GET_CHAT_ROOM";
export const GET_CHAT_ROOM_MEMBER = "GET_CHAT_ROOM_MEMBER";
