export const GET_PROFILE = "GET_PROFILE";
export const GET_CONNECTED_USER = "GET_CONNECTED_USER";
export const GET_CHAT_ROOM = "GET_CHAT_ROOM";
export const GET_CHAT_MEMBER = "GET_CHAT_MEMBER";
export const GET_CHAT_MESSAGE = "GET_CHAT_MESSAGE";
